version: "3"
services: 
  prodservice:
    build: ./product-service
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - mongo
      - rabbitmq
  orderservice:
    build: ./order-service
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - mongo
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - vmongoatelier203:/data/db
    restart: always

volumes:
  vmongoatelier203: 
