POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"produit 5",
    "description":"description produit 5",
    "price":300.6
}

###
POST http://localhost:3000/products/buy
Content-Type: application/json

["64188efa7c0c0048a1956bcc", "64187932c5fd1660e5ad6a71"]