POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"produit 3",
    "description":"description produit 3",
    "price":300.6
}

###
POST http://localhost:3000/products/buy
Content-Type: application/json

["64186ab04ec87c1c0f3ea73b", "64186ad44ec87c1c0f3ea73d"]